# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d1eb3fbf45e233b9595efa0352a91a1d444664d8c4296a0fc72db25ba178ff267644f6db8e9ea05192f69339fdc93d0924393aa1d19e6e7786dcf9a10fbfaa2a

test:
  secret_key_base: eeed4193b73f97747e3e1c8b61dd7940f82b077da75c69f759016c5c7dff2bdfc9652ad0f163c02adffb14369855e63189f7cc1d8fb11fc2481bbe6e8a10e99d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
